stages:
    - build
    - deploy
variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""


build-docker-frontend:
    stage: build
    image: docker:latest
    tags:
        - docker        
    services:
        - docker:dind
    script:
        - cd client/
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
        - docker -v
        - docker info
        - CCI_IMAGE_FRONTEND=${CI_REGISTRY}/${CI_PROJECT_PATH}:frontend-$(echo ${CI_COMMIT_REF_NAME} | cut -d'/' -f 2)
        - echo "Building Docker Image $CCI_IMAGE_FRONTEND ..."
        - docker build -t $CCI_IMAGE_FRONTEND .
        - echo "Pushing Docker Image..."
        - docker push $CCI_IMAGE_FRONTEND
build-docker-backend:
    stage: build
    image: docker:latest
    tags:
        - docker        
    services:
        - docker:dind
    script:
        - cd server/
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN ${CI_REGISTRY}
        - docker -v
        - docker info
        - CCI_IMAGE_BACKEND=${CI_REGISTRY}/${CI_PROJECT_PATH}:backend-$(echo ${CI_COMMIT_REF_NAME} | cut -d'/' -f 2)
        - echo "Building Docker Image $CCI_IMAGE_BACKEND ..."
        - docker build -t $CCI_IMAGE_BACKEND .
        - echo "Pushing Docker Image..."
        - docker push $CCI_IMAGE_BACKEND

deploy-portainer-stack:
    stage: deploy    
    image: docker:latest    
    script:
        - echo "Triggering deployment webhook..."